# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Install JavaCC and Ant
      run: brew install javacc ant

    - name: Replace the JavaCC path
      run: sed -i '.bak' 's,/opt/homebrew,/usr/local,' build.xml
      working-directory: java

    - name: Build with Ant
      run: ant compile
      working-directory: java
